export const storyGroupLabels: Record<string, string> = {
  "bg": "Story Backgrounds",
  "20": "Dossoles Holiday",
  "21": "Episode 09: Stormwatch",
  "23": "Near Light",
  "24": "Break the Ice",
  "25": "Invitation to Wine",
  "26": "Guide Ahead",
  "27": "Episode 10: Shatterpoint / Stultifera Navis",
  "28": "Lingering Echoes",
  "29": "Dorothy's Vision",
  "30": "Ideal City",
  "31": "An Obscure Wanderer",
  "32": "Episode 11: Return to Mist",
  "33": "Il Siracusano",
  "34": "What the Firelight Casts",
  "35": "Where Vernal Winds Will Never Blow",
  "37": "Episode 12: All Quiet Under the Thunder",
  "38": "Lone Trail",
  "39": "Hortus de Escapismo",
  "40": "The Black Forest Wills A Dream",
  "41": "So Long, Adele",
  "42": "Come Catastrophes or Wakes of Vultures",
  "43": "Episode 13: The Whirlpool that is Passion",
  "44": "Zwillingstürme im Herbst",
  "45": "The Rides to Lake Silberneherze",
  "46": "To the Grinning Valley",
  "47": "Here A People Sows",
  "48": "Operation Lucent Arrowhead",
  "49": "Babel",
  "50": "Episode 14: Absolved Will Be the Seekers",
  "51": "Path of Life",
  "52": "A Kazdelian Rescue",
  "53": "Adventure That Cannot Wait for the Sun",
  "54": "Delicious on Terra",
  "55": "Ending a Grand Overture",
  "56": "I Portatori dei Velluti",
  "57": "Exodus from the Pale Sea",
  "58": "Such is the Joy of Our Reunion / See You Soon",
  "59": "When Elegies Are Ashes",
  "60": "Episode 15: Dissociative Recombination",
  "61": "The Masses' Travels",
  "62": "Act or Die",
  "63": "Fantasy in The Mirage",
  "64": "Ato",
  "65": "Somniloquium Serenum",
  "ac1": "Grani and the Knights' Treasure",
  "ac3": "Heart of Surging Flame",
  "ac5": "Code of Brawl",
  "ac6": "Ancient Forge",
  "ac11": "Twilight of Wolumonde",
  "ac12": "The Great Chief Returns",
  "ac13": "Maria Nearl",
  "ac18": "Under Tides",
  "cc": "Contingency Contract",
  "cg": "CG",
  "item": "item_tll",
  "avg": "Story Images",
  "pic": "Integrated Strategies",
};