export const storyGroupLabels: Record<string, string> = {
  "bg": "Story Backgrounds",
  "20": "Dossoles Holiday",
  "21": "Episode 09: Stormwatch",
  "23": "Near Light",
  "24": "Break the Ice",
  "25": "Invitation to Wine",
  "26": "Guide Ahead",
  "27": "Episode 10: Shatterpoint",
  "28": "Lingering Echoes",
  "29": "Dorothy's Vision",
  "30": "Ideal City",
  "31": "An Obscure Wanderer",
  "32": "Episode 11: Return to Mist",
  "33": "Il Siracusano",
  "34": "What the Firelight Casts",
  "35": "Where Vernal Winds Will Never Blow",
  "37": "Episode 12: All Quiet Under the Thunder",
  "64": "Ato",
  "65": "Somniloquium Serenum",
  "avg": "Story Images",
  "pic": "Integrated Strategies",
};